# version: "3.9"

# services:
#   # Primary PostgreSQL server
#   postgres-master:
#     image: postgres:latest
#     environment:
#       POSTGRES_PASSWORD: password  # Replace with your password
#       POSTGRES_USER: postgres
#       POSTGRES_DB: mydatabase
#     volumes:
#       - postgres_master_data:/var/lib/postgresql/data

#   # Standby PostgreSQL server
#   postgres-slave:
#     image: postgres:latest
#     environment:
#       POSTGRES_PASSWORD: password  # Replace with your password
#       POSTGRES_USER: postgres
#       POSTGRES_DB: mydatabase
#       POSTGRES_REPLICATION_USER: repuser  # Replication user
#       POSTGRES_REPLICATION_PASSWORD: repuserpassword  # Replication user password
#     volumes:
#       - postgres_slave_data:/var/lib/postgresql/data
#     depends_on:
#       - postgres-master

# volumes:
#   postgres_master_data: {}
#   postgres_slave_data: {}
version: "3.9"

services:
  # Primary PostgreSQL server
  postgres-master:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password  # Replace with your password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432

  # Standby PostgreSQL server
  postgres-slave:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password  # Replace with your password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_REPLICATION_USER: repuser  # Replication user
      POSTGRES_REPLICATION_PASSWORD: repuserpassword  # Replication user password
    volumes:
      - postgres_slave_data:/var/lib/postgresql/data
    depends_on:
      - postgres-master

volumes:
  postgres_master_data: {}
  postgres_slave_data: {}
